### ISSUE TITLE
When deleting an activity, the activity cell still shows up but is blank

### ISSUE THREAD

**Issue by noahtallen** [jack-and-the-beans/buddies-ios#75]
To reproduce: 
1. Create a new activity. Use a well-populated topic like shopping because it's easier to see the bug when there are activities above and below the activity we're looking at
2. Go to the activity via topics
3. Delete the activity.
4. It will navigate back to topics, and you'll see a blank space where the activity used to be.

![delete_activity_bug](https://user-images.githubusercontent.com/6265975/53356579-b66b2c80-38f9-11e9-8b62-26123642d032.gif)

cc @lukemeierj thoughts?

**Comment by noahtallen** [comment]
Interestingly, when you put a breakpoint on `ActivityTableVC:140`, it does get hit, but when you navigate back to the page, it hits the breakpoint at least once for every cell on the page, and then again for the hidden activity at the end (I think)

**Comment by lukemeierj** [comment]
Looks like this problem has a couple things going on.

In master, the issue is from the `FilterSearchBar` component.  It looks like it uses cached ActivityIds, which won't work.

In #81, I pull the updating functionality out of the UI component and get rid of the caching problem

However, the problem is a little tricky because by the time we query Algolia for `ActivityId`s, the delete has not persisted to Algolia.  
<img width="925" alt="screen shot 2019-03-01 at 3 15 47 pm" src="https://user-images.githubusercontent.com/7787605/53663885-ef2a3f00-3c34-11e9-8351-fb514f413d70.png">
^ Reverse chronological order, we see that the Algolia entry is deleted _after_ the query.

**Comment by lukemeierj** [comment]
It looks like we can hide the problem by just setting the cells of non-existent activities to 0.

**Comment by noahtallen** [comment]
Thought: the activity cells shouldn't worry about the algolia query if it's deleted. Reason being that the listeners for activity x still exists, and will now fire with nil. I think the cell should know to not display anything if the listener tries to get an activity but it doesn't exist or is invalid. Similar to how view activity shouldn't care if a user DNE
  

  
  

  
  
>
