### ISSUE TITLE
Topic displays twice in viewActivity screen

### ISSUE THREAD

**Issue by lukemeierj** [jack-and-the-beans/buddies-ios#96]
<img width="361" alt="Screen Shot 2019-03-15 at 11 02 47 AM" src="https://user-images.githubusercontent.com/7787605/54440925-0166ab80-4712-11e9-8134-6d6ef3792091.png">

However, only one topic is in the activity 

<img width="471" alt="Screen Shot 2019-03-15 at 11 04 01 AM" src="https://user-images.githubusercontent.com/7787605/54441506-4ccd8980-4713-11e9-9ded-da8c81c92739.png">

Similar in concept to #13, but here the issue is in the view.  The correct value is saved.

**Comment by lukemeierj** [comment]
This also occurs on the ProfileVC.  It's probably related to #91

**Comment by noahtallen** [comment]
Holy cow this is all over the place. I'll investigate right now, since I'm doing some other view activity things

**Comment by noahtallen** [comment]
The actual `activityTopics` array inside view activity has duplicate values for every entry, it seems.

**Comment by noahtallen** [comment]
I think this is actually the same issue as #13. In this line:
```swift
let topicsArr = appDelegate.topicCollection.topics
```
Every single topic in that array is duplicated

**Comment by noahtallen** [comment]
In fact, if you look at the Topics tab, every topic is duplicated.

**Comment by noahtallen** [comment]
I've fixed this for both the profile and view activity. I make it so that getTopics always returns an array of unique topics. Doesn't fix the underlying issue, which is a combo of #13 and #92, both of which can cause the view to receive duplicate activities. For #13, there are duplicate topics in Topics, so it used to return all the matching topics, which included duplicate. For #92, the user doc would have duplicated topics IDs in the favorite topic collection, causing getTopics to try to get multiple for the same ID. Both of those issues are fixed **in the view**, but they still exist.
